language: go

go:
  - 1.9

env:
  - "PATH=$HOME/gopath/bin:$PATH"

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - ./test.sh
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
